Plausibility test bom refs
Festo-se/cyclonedx-editor-validator pull request #14
Opened 2023-06-13 16:47 UTC by chbk96

closes #5

2023-06-14 12:22 UTC, mmarseu requested changes
Shouldn't this check be part of the *validate* command? It is certainly a type of validation.  
If it remains a separate command, `available_commands.md` should be updated.

IMO, the check that all bom-refs are unique is missing. Your code depends on this assumption but doesn't make sure it is correct. Again, this would be better suited for the *validate* command, because it is a requirement in the spec. It just can't be expressed in JSON schema.

2023-06-14 12:22 UTC, mmarseu commented on cdxev/plausibility_check.py
> +        # also checks that every component is depended on
This is a misinterpretation of CycloneDX. Not all components in an SBOM are required to be part of the same dependency tree.

That is why *dependencies* and *assemblies* are both a thing in CycloneDX. There are products assembled from multiple components, where there is no *depends-on* relationship but rather an *is-part-of* relationship.

2023-06-14 18:47 UTC, italvi commented
> Shouldn't this check be part of the _validate_ command? It is certainly a type of validation. If it remains a separate command, `available_commands.md` should be updated.
> 
> IMO, the check that all bom-refs are unique is missing. Your code depends on this assumption but doesn't make sure it is correct. Again, this would be better suited for the _validate_ command, because it is a requirement in the spec. It just can't be expressed in JSON schema.

Agree, though this should not be a default check when executing validate and be controlled through a flag. 

Regarding the uniqueness of `bom-ref` within **whole** (for `dependsOn` the `uniqueItems` property is already used) SBOM you are correct, seems like `jsonschema` does not support unique key-value pairs, [yet](https://github.com/python-jsonschema/check-jsonschema/issues/60). But easy to loop through the SBOM and do this check ourselves.

2023-07-04 05:54 UTC, italvi commented on cdxev/__main__.py
> +        ),
Why this additional choice? Why not providing the flag `plausibility-check` means `true`?

2023-07-04 07:05 UTC, italvi requested changes

2023-07-04 12:35 UTC, chbk96 commented on tests/test_validate.py
> +)
adapting the tests for plausibility to this one is, and in doing so changing it to fit the requirements, would be work, that seemed unnecessary

2023-07-04 13:06 UTC, chbk96 commented on tests/test_validate.py
> +)
removed

2024-07-02 13:28 UTC, mmarseu commented
Has this PR been abandoned? It's been in my todo list forever but now I'm not even sure there is a point in reviewing this anymore.

2024-07-03 08:03 UTC, CBeck-96 commented
> Has this PR been abandoned? It's been in my todo list forever but now I'm not even sure there is a point in reviewing this anymore.

Considering there are other priorities and demand seems low, i will close it for the time beeing and tackle the subject at a more oppurtune time (propably version 1.0 or higher).

2024-07-03 08:03 UTC, closed without merging

2024-07-03 08:04 UTC, CBeck-96 commented
Considering there are other priorities and demand seems low, i will close it for the time beeing and tackle the subject at a more oppurtune time (propably version 1.0 or higher).