fix: remove bom-refs only for deleted components in build public
Festo-se/cyclonedx-editor-validator pull request #196
Opened 2024-06-03 14:09 UTC by CBeck-96

closes #154

2024-06-26 09:05 UTC, mmarseu approved these changes
As requested, I tried the changes without reviewing the code. LGTM.

2024-06-27 05:57 UTC, italvi requested changes

2024-06-27 05:57 UTC, italvi commented on cdxev/build_public_bom.py
> +    print(kept_bom_refs)
debug print?

2024-06-27 05:57 UTC, italvi commented on tests/test_sbom_functions.py
Is this really necessary to include this now? I would add this into #157 - there is even already a "sbomFunctionsTests.py".

2024-06-27 08:05 UTC, CBeck-96 commented on tests/test_sbom_functions.py
I havent had time to look at #157 yet. Where should i put the test instead, (falsly )in test_merge like the others?

2024-06-27 08:13 UTC, mmarseu commented on tests/test_sbom_functions.py
#157 is about integration tests. This is a unit test, isn't it?

2024-06-27 08:24 UTC, CBeck-96 commented on cdxev/build_public_bom.py
> +    print(kept_bom_refs)
Propably

2024-06-28 05:30 UTC, italvi commented on tests/test_sbom_functions.py
Ok, let me change my intention, why this new file? What is the purpose of [sbomFunctionTest.py](https://github.com/Festo-se/cyclonedx-editor-validator/blob/154-build-public-messes-up-compositions/tests/auxiliary/sbomFunctionsTests.py)? Seems to be a forgotten file, @mmarseu?

2024-06-28 16:41 UTC, CBeck-96 commented on tests/test_sbom_functions.py
Files are cnsolidated

2024-07-01 09:09 UTC, mmarseu commented on tests/test_sbom_functions.py
@CBeck-96 To avoid confusion you could rename the filer to `helper.py` or some other commonly used name for that sort of thing.

2024-07-03 11:14 UTC, CBeck-96 commented on tests/test_sbom_functions.py
Done in #215

2024-07-04 05:13 UTC, italvi requested changes
After including the compositions from #154 just for double-check into my SBOM, where the `bom-ref`s are not used for any component, I made the observation that you delete the `bom-ref`s.

Looking at your code, you are using `list_of_components` to get your `bom-ref`s and as they are not within the `components` you remove the `bom-ref`s in `composition`. This is definitely a "plausibility check", not something I would expect from `build-public`. Therefore, please change this behavior.

Do you agree, @mmarseu? (Let's not talk about the irony that we just closed the PR #14 for plausibility check 😆)

2024-07-04 06:35 UTC, mmarseu commented
> After including the compositions from #154, just for double-check, into my SBOM, where the `bom-ref`s are not used for any component, I made the observation that you delete the `bom-ref`s.
> 
> Looking at your code, you are using `list_of_components` to get your `bom-ref`s and as they are not within the `components` of my SBOM you remove the `bom-ref`s from #154 in `composition`. This is definitely a "plausibility check", not something I would expect from `build-public`. Therefore, please change this behavior.
> 
> Do you agree, @mmarseu? (Let's not talk about the irony that we just closed the PR #14 for plausibility check 😆)

Yes, I agree. `build-public` should strictly only delete bom-refs for deleted components

2024-07-05 12:51 UTC, italvi approved these changes

2024-07-05 12:53 UTC, merged