refactor: *validate* report options
Festo-se/cyclonedx-editor-validator pull request #204
Opened 2024-06-11 07:44 UTC by mmarseu

This PR reworks the command-line options for report creation in the *validate* command.

Previously:

- `--report-format` could be set to
  - `stdout`, which prints all results in normal log format to stdout.
  - `warnings-ng`
  - `gitlab-code-quality`
- `--output` option was to provide a path where to write the report.

This was confusing because the interaction between both arguments wasn't clear (what if you set `stdout` but still provide an `--output` or no `--output` but still a `--report-format`?) and because the help text for `--output` was wrong (it was reused from other commands which output SBOMs, not validation reports).

This PR makes these changes:

- Remove `stdout` option from `--report-format`
- Rename `--output` to `--report-path`
- Make is so either both options must be passed or neither

2024-06-24 20:48 UTC, CBeck-96 requested changes
The documentation still contains the old examples:

    cdx-ev validate bom.json --report-format=warnings-ng" # writes issues to a file "issues.json" and stdout
    cdx-ev validate bom.json --report-format=warnings-ng --output=myfile.json" # write issues to a file "myfile.json" and stdout
    cdx-ev validate bom.json --report-format=gitlab-code-quality # writes issues to a file "issues.json" and stdout


The new depdendency should be mentioned as well.

2024-06-26 11:09 UTC, mmarseu commented
> The documentation still contains the old examples:
> 
> ```
> cdx-ev validate bom.json --report-format=warnings-ng" # writes issues to a file "issues.json" and stdout
> cdx-ev validate bom.json --report-format=warnings-ng --output=myfile.json" # write issues to a file "myfile.json" and stdout
> cdx-ev validate bom.json --report-format=gitlab-code-quality # writes issues to a file "issues.json" and stdout
> ```
> 
> The new depdendency should be mentioned as well.

By new dependency you mean the two options `--report-format` and `--report-path`? Because I can't see that I've introduced a new dependency to the project in this PR.

I've updates this section in the latest change.

2024-06-26 11:39 UTC, CBeck-96 commented
> > The documentation still contains the old examples:
> > ```
> > cdx-ev validate bom.json --report-format=warnings-ng" # writes issues to a file "issues.json" and stdout
> > cdx-ev validate bom.json --report-format=warnings-ng --output=myfile.json" # write issues to a file "myfile.json" and stdout
> > cdx-ev validate bom.json --report-format=gitlab-code-quality # writes issues to a file "issues.json" and stdout
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The new depdendency should be mentioned as well.
> 
> By new dependency you mean the two options `--report-format` and `--report-path`? Because I can't see that I've introduced a new dependency to the project in this PR.
> 
> I've updates this section in the latest change.

Sorry, mistake on my part, i meant exactly those commands/command names.

2024-06-26 11:46 UTC, CBeck-96 approved these changes

2024-06-27 20:59 UTC, italvi approved these changes

2024-06-27 21:00 UTC, merged