feat: add hierarchical option to merge command
Festo-se/cyclonedx-editor-validator pull request #338
Opened 2024-12-15 01:45 UTC by CBeck-96

closes #152

2024-12-17 07:31 UTC, italvi requested changes
The coverage of 94% got me confused, but it seems we still have 95%, so that's why the pipeline did not break.
![image](https://github.com/user-attachments/assets/a9e93180-a8d1-4536-94aa-1d9ab52ceb25)

Further I noticed two bugs:
During testing the `hierarchical` flag, I observed the following bug:
If I have an SBOM with `components` within a `component` of `components`, i.e.
```json
{
    "$schema": "http://cyclonedx.org/schema/bom-1.4.schema.json",
    "bomFormat": "CycloneDX",
    "specVersion": "1.4",
    "version": 1,
    "metadata": {
        "tools": [
            {
                "vendor": "@cyclonedx",
                "name": "cyclonedx-library",
                "version": "1.13.3",
                "externalReferences": [
                    {
                        "url": "https://github.com/CycloneDX/cyclonedx-javascript-library/issues",
                        "type": "issue-tracker",
                        "comment": "as detected from PackageJson property \"bugs.url\""
                    },
                    {
                        "url": "git+https://github.com/CycloneDX/cyclonedx-javascript-library.git",
                        "type": "vcs",
                        "comment": "as detected from PackageJson property \"repository.url\""
                    },
                    {
                        "url": "https://github.com/CycloneDX/cyclonedx-javascript-library#readme",
                        "type": "website",
                        "comment": "as detected from PackageJson property \"homepage\""
                    }
                ]
            },
            {
                "vendor": "@cyclonedx",
                "name": "cyclonedx-npm",
                "version": "1.9.2",
                "externalReferences": [
                    {
                        "url": "https://github.com/CycloneDX/cyclonedx-node-npm/issues",
                        "type": "issue-tracker",
                        "comment": "as detected from PackageJson property \"bugs.url\""
                    },
                    {
                        "url": "git+https://github.com/CycloneDX/cyclonedx-node-npm.git",
                        "type": "vcs",
                        "comment": "as detected from PackageJson property \"repository.url\""
                    },
                    {
                        "url": "https://github.com/CycloneDX/cyclonedx-node-npm#readme",
                        "type": "website",
                        "comment": "as detected from PackageJson property \"homepage\""
                    }
                ]
            }
        ],
        "component": {
            "type": "application",
            "name": "juice-shop",
            "version": "14.1.1",
            "bom-ref": "juice-shop@14.1.1",
            "author": "Björn Kimminich",
            "description": "Probably the most modern and sophisticated insecure web application",
            "licenses": [
                {
                    "license": {
                        "id": "MIT"
                    }
                }
            ],
            "purl": "pkg:npm/juice-shop@14.1.1?vcs_url=git%2Bhttps%3A//github.com/juice-shop/juice-shop.git",
            "externalReferences": [
                {
                    "url": "https://github.com/juice-shop/juice-shop/issues",
                    "type": "issue-tracker",
                    "comment": "as detected from PackageJson property \"bugs.url\""
                },
                {
                    "url": "git+https://github.com/juice-shop/juice-shop.git",
                    "type": "vcs",
                    "comment": "as detected from PackageJson property \"repository.url\""
                },
                {
                    "url": "https://owasp-juice.shop",
                    "type": "website",
                    "comment": "as detected from PackageJson property \"homepage\""
                }
            ],
            "properties": [
                {
                    "name": "cdx:npm:package:path",
                    "value": ""
                },
                {
                    "name": "cdx:npm:package:private",
                    "value": "true"
                }
            ]
        }
    },
    "components": [
        {
            "type": "library",
            "name": "node-pre-gyp",
            "group": "@mapbox",
            "version": "1.0.10",
            "bom-ref": "@mapbox/node-pre-gyp@1.0.10",
            "author": "Dane Springmeyer",
            "description": "Node.js native addon binary install tool",
            "hashes": [
                {
                    "alg": "SHA-512",
                    "content": "e324a8e028f34adba9accc24df91f9a4f6e4ca68efd521778c62e3eab007a7fc53fd117b4cbedb77d0939b5c43638f4adaa17b8e647f83b93e4a42c44cfea8a4"
                }
            ],
            "licenses": [
                {
                    "license": {
                        "id": "BSD-3-Clause"
                    }
                }
            ],
            "purl": "pkg:npm/%40mapbox/node-pre-gyp@1.0.10",
            "externalReferences": [
                {
                    "url": "https://registry.npmjs.org/@mapbox/node-pre-gyp/-/node-pre-gyp-1.0.10.tgz",
                    "type": "distribution",
                    "comment": "as detected from npm-ls property \"resolved\""
                },
                {
                    "url": "https://github.com/mapbox/node-pre-gyp/issues",
                    "type": "issue-tracker",
                    "comment": "as detected from PackageJson property \"bugs.url\""
                },
                {
                    "url": "git://github.com/mapbox/node-pre-gyp.git",
                    "type": "vcs",
                    "comment": "as detected from PackageJson property \"repository.url\""
                },
                {
                    "url": "https://github.com/mapbox/node-pre-gyp#readme",
                    "type": "website",
                    "comment": "as detected from PackageJson property \"homepage\""
                }
            ],
            "properties": [
                {
                    "name": "cdx:npm:package:path",
                    "value": "node_modules/@mapbox/node-pre-gyp"
                }
            ],
            "components": [
                {
                    "type": "library",
                    "name": "ansi-regex",
                    "version": "5.0.1",
                    "bom-ref": "@mapbox/node-pre-gyp@1.0.10|ansi-regex@5.0.1",
                    "author": "Sindre Sorhus",
                    "description": "Regular expression for matching ANSI escape codes",
                    "hashes": [
                        {
                            "alg": "SHA-512",
                            "content": "aae2505e54d25062f62c7f52517a3c570b18e2ca1a9e1828e8b3529bce04d4b05c13cb373b4c29762473c91f73fd9649325316bf7eea38e6fda5d26531410a15"
                        }
                    ],
                    "licenses": [
                        {
                            "license": {
                                "id": "MIT"
                            }
                        }
                    ],
                    "purl": "pkg:npm/ansi-regex@5.0.1",
                    "externalReferences": [
                        {
                            "url": "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz",
                            "type": "distribution",
                            "comment": "as detected from npm-ls property \"resolved\""
                        },
                        {
                            "url": "https://github.com/chalk/ansi-regex/issues",
                            "type": "issue-tracker",
                            "comment": "as detected from PackageJson property \"bugs.url\""
                        },
                        {
                            "url": "git+https [...]

2024-12-17 23:12 UTC, CBeck-96 commented on cdxev/__main__.py
>          help="Path to a folder with sboms to be merged",
Done

2024-12-17 23:12 UTC, CBeck-96 commented on cdxev/__main__.py
> +        help="Flag to determine if the components should be merged hierarchical",
Done

2025-01-07 05:23 UTC, CBeck-96 commented on tests/auxiliary/helper.py
> +def create_components() -> dict:
removed

2025-01-07 05:24 UTC, CBeck-96 commented on docs/source/usage/merge.rst
> +The ``--hierarchical`` flag allows for hierarchical merges.
added a picture for clarification

2025-01-26 10:42 UTC, italvi requested changes
The `hierarchical` flag seems to work now, however, if I have a `components` within a `components` of a component, i.e.
```json
{
    "components": [
        {
            "type": "library",
            "name": "node-pre-gyp",
            "group": "@mapbox",
            "version": "1.0.10",
            "bom-ref": "@mapbox/node-pre-gyp@1.0.10",
            "author": "Dane Springmeyer",
            "description": "Node.js native addon binary install tool",
            "hashes": [
                {
                    "alg": "SHA-512",
                    "content": "e324a8e028f34adba9accc24df91f9a4f6e4ca68efd521778c62e3eab007a7fc53fd117b4cbedb77d0939b5c43638f4adaa17b8e647f83b93e4a42c44cfea8a4"
                }
            ],
            "licenses": [
                {
                    "license": {
                        "id": "BSD-3-Clause"
                    }
                }
            ],
            "purl": "pkg:npm/%40mapbox/node-pre-gyp@1.0.10",
            "externalReferences": [
                {
                    "url": "https://registry.npmjs.org/@mapbox/node-pre-gyp/-/node-pre-gyp-1.0.10.tgz",
                    "type": "distribution",
                    "comment": "as detected from npm-ls property \"resolved\""
                },
                {
                    "url": "https://github.com/mapbox/node-pre-gyp/issues",
                    "type": "issue-tracker",
                    "comment": "as detected from PackageJson property \"bugs.url\""
                },
                {
                    "url": "git://github.com/mapbox/node-pre-gyp.git",
                    "type": "vcs",
                    "comment": "as detected from PackageJson property \"repository.url\""
                },
                {
                    "url": "https://github.com/mapbox/node-pre-gyp#readme",
                    "type": "website",
                    "comment": "as detected from PackageJson property \"homepage\""
                }
            ],
            "properties": [
                {
                    "name": "cdx:npm:package:path",
                    "value": "node_modules/@mapbox/node-pre-gyp"
                }
            ],
            "components": [
                {
                    "type": "library",
                    "name": "ansi-regex",
                    "version": "5.0.1",
                    "bom-ref": "@mapbox/node-pre-gyp@1.0.10|ansi-regex@5.0.1",
                    "author": "Sindre Sorhus",
                    "description": "Regular expression for matching ANSI escape codes",
                    "hashes": [
                        {
                            "alg": "SHA-512",
                            "content": "aae2505e54d25062f62c7f52517a3c570b18e2ca1a9e1828e8b3529bce04d4b05c13cb373b4c29762473c91f73fd9649325316bf7eea38e6fda5d26531410a15"
                        }
                    ],
                    "licenses": [
                        {
                            "license": {
                                "id": "MIT"
                            }
                        }
                    ],
                    "purl": "pkg:npm/ansi-regex@5.0.1",
                    "externalReferences": [
                        {
                            "url": "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz",
                            "type": "distribution",
                            "comment": "as detected from npm-ls property \"resolved\""
                        },
                        {
                            "url": "https://github.com/chalk/ansi-regex/issues",
                            "type": "issue-tracker",
                            "comment": "as detected from PackageJson property \"bugs.url\""
                        },
                        {
                            "url": "git+https://github.com/chalk/ansi-regex.git",
                            "type": "vcs",
                            "comment": "as detected from PackageJson property \"repository.url\""
                        },
                        {
                            "url": "https://github.com/chalk/ansi-regex#readme",
                            "type": "website",
                            "comment": "as detected from PackageJson property \"homepage\""
                        }
                    ],
                    "properties": [
                        {
                            "name": "cdx:npm:package:path",
                            "value": "node_modules/@mapbox/node-pre-gyp/node_modules/ansi-regex"
                        }
                    ]
                }
            ]
          }
     ]
 }

Then it does not work as you describe it in the documentation: The component "ansi-regex" is still just copied within "node-pre-gyp" and not separately on the highest level.

2025-01-26 10:42 UTC, italvi commented on docs/source/usage/merge.rst
> +The merge is per default not hierarchical for the ``components`` field of a ``component`` (`see CycloneDX documentation <https://cyclonedx.org/docs/1.6/json/#components_items_components>`). This mean
you provide the link in a wrong way: You are missing the underscore after the apostrophe, i.e. `_, leading to a wrong representation:
![image](https://github.com/user-attachments/assets/f959ba7a-d3b6-4eba-8525-f8bc1e5cea1c)

and it should be only CycloneDX documentation, the "see" should not be included as you are not referring to the word "see" but the documentation.

2025-01-26 10:42 UTC, italvi commented on cdxev/merge.py
> +    param present_components: a list of component identities that are already present in the sbom.
SBOM

2025-01-26 10:42 UTC, italvi commented on cdxev/merge.py
> +    param new_components: a list of components that shell be compared against the list of already
shall

2025-01-26 10:42 UTC, italvi commented on cdxev/merge.py
> +    param kept_components: list of components not present in the list of provided components,
dot at end of the sentence.

2025-01-26 10:42 UTC, italvi commented on cdxev/merge.py
> +    param dropped_components: list of components that are already present
dot at end of the sentence + kind of confusing as there is already the `present_component` variable describing the same functionality.

2025-01-26 10:42 UTC, italvi commented on cdxev/merge.py
> +    param add_to_existing: list of nested components that have to be added to present components
dot at end of the sentence + should be either present_components or adjust the present_components to present_components in [L#33](https://github.com/Festo-se/cyclonedx-editor-validator/pull/338/files#diff-9b28318ee8ce015ce5d42609086ae25efa5d528b3fcb84ee73e1014f3fe815dfR33).

2025-01-26 10:42 UTC, italvi commented on cdxev/merge.py
> +        # component is new
it sounds strange that you iterate through "new_components" but then compare whether a component is new or already present.

2025-01-26 10:42 UTC, italvi commented on cdxev/merge.py
> +        # while doing so, the algorithm checks, that the sbom does not
Capitalized "w", i.e. While + SBOM

2025-01-26 10:42 UTC, italvi commented on cdxev/merge.py
> +        # that component's bom-ref will be renamed
dot at end of the sentence.

2025-01-26 10:42 UTC, italvi commented on cdxev/merge.py
> +                # The new bom-ref must not appear in either of the sboms
SBOMs

2025-01-26 10:42 UTC, italvi commented on tests/test_merge.py
Why are you creating new entries here, instead of providing the necessary SBOMs? You are creating a lot of code, which is not the test itself, making it hard to understand which case is currently tested. Using a dedicated SBOM makes it definitely more readable.

2025-01-26 10:42 UTC, italvi commented on tests/integration/test_integration.py
Would be good to also add a test for the `warning` message, i.e. dropping a duplicate component.

2025-01-31 10:13 UTC, CBeck-96 commented on cdxev/merge.py
> +    param dropped_components: list of components that are already present
The dropped_components is needed for the bom-ref functionality. That necessity will dissapear through the changes of #356 and can be removed after merging the two/ during the rebase needed.

2025-01-31 10:18 UTC, CBeck-96 commented on cdxev/merge.py
> +        # component is new
renamed -> components_to_add

2025-02-03 10:52 UTC, CBeck-96 commented on tests/test_merge.py
removed

2025-02-03 10:53 UTC, CBeck-96 commented on cdxev/merge.py
> +                # The new bom-ref must not appear in either of the sboms
Done

2025-02-03 10:53 UTC, CBeck-96 commented on cdxev/merge.py
> +        # that component's bom-ref will be renamed
Done

2025-02-03 10:53 UTC, CBeck-96 commented on cdxev/merge.py
> +        # while doing so, the algorithm checks, that the sbom does not
done

2025-02-03 10:54 UTC, CBeck-96 commented on cdxev/merge.py
> +    param present_components: a list of component identities that are already present in the sbom.
done

2025-02-03 10:55 UTC, CBeck-96 commented on cdxev/__main__.py
> +        help="Path to a folder with SBOMs to be merged",
done

2025-02-03 11:07 UTC, CBeck-96 commented on docs/source/usage/merge.rst
> +The merge is per default not hierarchical for the ``components`` field of a ``component`` (`see CycloneDX documentation <https://cyclonedx.org/docs/1.6/json/#components_items_components>`). This mean
done

2025-02-03 12:13 UTC, CBeck-96 commented on tests/integration/test_integration.py
In

2025-02-03 21:46 UTC, italvi requested changes
Small changes for the comments, should be "fixed" fast, then I can approve it.

2025-02-03 21:46 UTC, italvi commented on cdxev/merge.py
> +    param new_components: a list of components that shall be compared against the list of already
The variable `new_components` does not exist anymore.

2025-02-03 21:46 UTC, italvi commented on cdxev/merge.py
> +    param dropped_components: list of components that are already present
Fine for me, as long you don't forget it.

2025-02-03 21:46 UTC, italvi commented on docs/source/usage/merge.rst
> +The merge is per default not hierarchical for the ``components`` field of a ``component`` (`CycloneDX documentation <https://cyclonedx.org/docs/1.6/json/#components_items_components>`_). This means t
possessive apostrophe after SBOMs, to indicate that the components section belong to the SBOM, i.e. SBOMs'

2025-02-03 21:46 UTC, italvi commented on tests/test_merge.py
though it's still nested with some field "manipulation", it's a little bit more readable now, so let's keep it us at is, until they once fail and there will be some issues understanding the tests.

2025-02-04 09:42 UTC, italvi requested changes

2025-02-04 09:42 UTC, italvi commented on cdxev/merge.py
> +    param components_to_add: list of components that are already present.
now you have this variable twice, please remove one of them.

2025-02-05 09:42 UTC, italvi approved these changes
As all requested changes are implemented now: LGTM.

2025-02-05 09:42 UTC, merged