feat: add 'vex' option
Festo-se/cyclonedx-editor-validator pull request #342
Opened 2024-12-16 14:26 UTC by Matze08

closes #156

2025-01-08 03:31 UTC, CBeck-96 requested changes

2025-01-08 03:31 UTC, CBeck-96 commented on cdxev/vex.py
> +            list_str += (vulnerability.get("id")) + "\n"
Id is not a required field (you should never assume a key from user input exists in general). 
If not id is present, the program crashes "TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'"
get("id") -> get("id", "") 

Also, if no id is present, consider the references field, this might contain an id
https://cyclonedx.org/docs/1.6/json/#vulnerabilities_items_references_items_id

2025-01-08 03:31 UTC, CBeck-96 commented on cdxev/vex.py
> +        if vulnerability.get("id", []) == id:
Take the references field into consideration, you might encounter cases like
{
  "id": "SNYK-PYTHON-ENROCRYPT-1912876",
  "references": [
    {
      "id:" "CVE-2021-39182",
      "source": "https://nvd.nist.gov/vuln/detail/CVE-2021-39182"
    }
  ]
}
The  command should still be able to find this vulnerability if siomeone searches for the CVE entry.

2025-01-08 03:31 UTC, CBeck-96 commented on cdxev/vex.py
> +        raise ValueError(
That should error should already be catched by the parser.

2025-01-08 03:31 UTC, CBeck-96 commented on cdxev/vex.py
> +        if vulnerability.get("analysis", []).get("state", []) == state:
If no analysis field is present the program crashes since you call list.get().
=> .get("analysis", {}).get("state", "")

2025-01-08 03:31 UTC, CBeck-96 commented on cdxev/vex.py
> +                + vulnerability.get("analysis").get("state")
Same as below, do not assume that the keys are present.

2025-01-08 03:31 UTC, CBeck-96 commented on cdxev/vex.py
> +    output_file["bomFormat"] = input_file.get("bomFormat", [])
Since the types of those fields are str/int you should return a corresponding type.

2025-01-08 03:31 UTC, CBeck-96 commented on tests/test_vex.py
> +
Add test cases for "flawed" inputs, like vex files without id, analysis field etc.
Those should not lead to crashes.

2025-01-17 08:42 UTC, CBeck-96 requested changes
Why so many vex files in test? You could just create one file containing all cases and test the functions with them. 
The current version is harder to maintain in case of changes to the specification and if your inpout is to specific you might miss some error sources.

2025-01-17 08:42 UTC, CBeck-96 commented on cdxev/vex.py
> +            vul_ref_id = vulnerability.get("references", {}).get("id", "-")
"references" is a list of objects that can contain several references:
https://cyclonedx.org/docs/1.6/json/#vulnerabilities_items_references

2025-01-17 08:42 UTC, CBeck-96 commented on cdxev/vex.py
> +                + vulnerability.get("references", {}).get("id", "-")
Same as above
If only one ID is added, how is decided which one?

2025-01-17 08:42 UTC, CBeck-96 commented on tests/auxiliary/test_vex/searched_vex_missing_data.json
> +            "references": {
Inavlid vex: references should be a list of objects

2025-01-17 08:42 UTC, CBeck-96 commented on tests/test_vex.py
> +        with open(
Avoid repetitive code: create a function like "load_test_vex_file()" or load_test_vex_file_json/csv()  that receives the file name as input and returns the file content.

2025-01-17 08:42 UTC, CBeck-96 commented on cdxev/vex.py
> +            or vulnerability.get("references", {}).get("id", "") == id
You have to search the list

2025-01-17 08:42 UTC, CBeck-96 commented on cdxev/vex.py
> +    searched_vulnerability = []
The name can be misleading, since "searched" implies looked into, not found/matched and since its a list "vulnerabilities" in plural would be a better choice.

2025-01-17 08:42 UTC, CBeck-96 commented on cdxev/__main__.py
> +    search_parser = subparsers.add_parser("search", help="Get vulnerability by ID.")
vulnerabilities, since several can be returned

2025-01-17 08:49 UTC, CBeck-96 commented on cdxev/vex.py
> +            vul_ref_id = vulnerability.get("references", {}).get("id", "-")
you can test the code with this: https://github.com/CycloneDX/bom-examples/blob/master/VEX/vex.json it should include at least the minimum of fields.

2025-02-12 15:38 UTC, CBeck-96 requested changes

2025-02-13 13:53 UTC, CBeck-96 submitted a review, later dismissed

2025-02-16 15:40 UTC, italvi requested changes

2025-02-16 15:40 UTC, italvi commented on cdxev/__main__.py
> +        help="Executes commands [list, search, trim, extract] on VEX/SBOM files.",
Should not include the commands itself to the help. Otherwise you always have to adjust and keep it in mind. The help-function itself will already show the subcommands.

2025-02-16 15:40 UTC, italvi commented on cdxev/__main__.py
> +        "--scheme",
It's "schema", not scheme.

2025-02-16 15:40 UTC, italvi commented on cdxev/__main__.py
> +        help="Set scheme of return list.",
schema

2025-02-16 15:40 UTC, italvi commented on cdxev/__main__.py
> +        help="Trims a VEX to show only the vulnerabilities according to the selected state.",
Why trim is only depending on the `state`? Why not also e.g. on `severity`, maybe I want to only have vulnerabilities with critical severity.

2025-02-16 15:40 UTC, italvi commented on cdxev/__main__.py
> +        ],
I would refer from using choices for the state. If the states change sometimes e.g. due to specification changes, you have to differentiate between versions. Something you really should avoid. Why not just compare the value with the value within `state`? If it does not equal anything, you simply can ignore the entry. I do understand that you want to help the user, but somebody working with the VEX here, will have the documentation in mind.

2025-02-16 15:40 UTC, italvi commented on cdxev/__main__.py
> +        scheme = args.scheme
schema

2025-02-16 15:40 UTC, italvi commented on cdxev/vex.py
> +    Copy important keys and values from input_file to output_file
dot at end of sentence

2025-02-16 15:40 UTC, italvi commented on cdxev/vex.py
> +    Get a file with vulnerabilities filtered by state
dot at end of the sentence

2025-02-16 15:40 UTC, italvi commented on cdxev/vex.py
> +    Extract the vulnerabilities of a SBOM file to a VEX file
dot at end of sentence

2025-02-16 15:40 UTC, italvi commented on cdxev/vex.py
> +        A SBOM dictionary from which the vulnerabilities should be extracted.
An SBOM

2025-02-16 15:40 UTC, italvi commented on cdxev/vex.py
> +        A SBOM dictionary from which the vulnerabilities should be extracted.
remove dot at end of sentence as you never used it before for the input/output

2025-02-16 15:40 UTC, italvi commented on cdxev/vex.py
> +    Get different information about vulnerabilities in VEX file
dot at end of the sentence

2025-02-16 15:40 UTC, italvi commented on docs/source/usage/vex.rst
> +    * ``extract``: extract all vulnerabilities from a SBOM-file to a VEX-file
dot at the end of all the sentences

2025-02-16 15:40 UTC, italvi commented on docs/source/usage/vex.rst
> +    * ``extract``: extract all vulnerabilities from a SBOM-file to a VEX-file
an SBOM

2025-02-16 15:40 UTC, italvi commented on docs/source/usage/vex.rst
> +    This subcommand returns a json file which contains only filtered vulnerabilities. The vulnerabilities can be filtered by their state. The following states are supported:
As mentioned in the code, you should not rely on the enum state.

2025-02-16 15:40 UTC, italvi commented on cdxev/vex.py
> +            vul_description = vulnerability.get("description", "-")
you are not sanitizing the input, so if e.g. the description has "\n" in it, it introduces this within your output, e.g.

			"description": "Microsoft is releasing this security advisory to provide information about a vulnerability in .NET 6.0, .NET 5.0 and .NET Core 3.1. This advisory also provides guidance on what developers can do to update their applications to remove this vulnerability.\n\nA vulnerability exists in .NET 6.0, .NET 5.0 and .NET core 3.1 where a malicious client can manipulate cookies and cause a Denial of Service.\n\n###Affected Software

Results in:
![image](https://github.com/user-attachments/assets/6da605f7-d686-4db5-933f-27dc1ad7a1b8)

2025-02-20 12:10 UTC, italvi requested changes
Please also add it in the command overview of the [README.md](https://github.com/Festo-se/cyclonedx-editor-validator/blob/vex_command/README.md#command-overview).

2025-03-17 21:28 UTC, italvi requested changes
@CBeck-96 please see my comments. Only the implementation of the key-value pair is not the same as for the `set`-command. Otherwise only grammar issues and I only tested `list`, `search` and `extract` as I want to wait for the new implementation of `trim`.

2025-03-17 21:28 UTC, italvi commented on cdxev/vex.py
> +    Returns True if found, False if not found
dot at end of the sentence

2025-03-22 11:44 UTC, CBeck-96 commented on docs/source/usage/vex.rst
> +    This subcommand returns a json file which contains only filtered vulnerabilities. The vulnerabilities can be filtered by any key-value pair.
Done

2025-03-22 11:45 UTC, CBeck-96 commented on cdxev/vex.py
> +    Returns True if found, False if not found
Done

2025-03-23 19:27 UTC, CBeck-96 commented on cdxev/__main__.py
> +        type=str,
changed

2025-03-23 19:37 UTC, CBeck-96 commented on README.md
> +| [vex](https://festo-se.github.io/cyclonedx-editor-validator/usage/vex.html) | Apply different sub-commands on VEX- or embedded VEX-files. |
changed

2025-03-23 21:09 UTC, italvi commented on cdxev/__main__.py
> +        type=str,
using `vex trim --help` now leads to an error 
![image](https://github.com/user-attachments/assets/a154d6f5-85cf-4dab-8d06-10ac497a6f37)

2025-03-23 21:14 UTC, italvi commented on cdxev/__main__.py
> +        "key",
it should be "--key", see https://github.com/Festo-se/cyclonedx-editor-validator/blob/vex_command/cdxev/__main__.py#L684

2025-03-23 21:14 UTC, italvi commented on cdxev/__main__.py
> +        "value",
should be `--value`, see https://github.com/Festo-se/cyclonedx-editor-validator/blob/vex_command/cdxev/__main__.py#L692

2025-03-25 10:23 UTC, CBeck-96 commented on cdxev/__main__.py
> +            write_sbom(output, args.output, update_metadata=False)
now should be list_file_bom.txt

2025-03-25 10:24 UTC, CBeck-96 commented on cdxev/__main__.py
> +        type=str,
fixed

2025-03-25 10:25 UTC, CBeck-96 commented on cdxev/__main__.py
> +        "key",
Then it must later be checked, that both are prsent, while set also allows the from file method, here we only have the key value method, so it makes sense to make them mandatory.

2025-03-25 10:26 UTC, CBeck-96 commented on cdxev/__main__.py
> +        "value",
See above comment

2025-04-20 20:43 UTC, italvi requested changes
Only documentation changes, then it can be approved.

2025-04-20 20:43 UTC, italvi commented on docs/source/usage/vex.rst
> +        CVE-1013-0003
This looks really ugly:
![image](https://github.com/user-attachments/assets/c138f63a-764f-410c-8c8b-34706ff532ec)

2025-04-20 20:43 UTC, italvi commented on docs/source/usage/vex.rst
> +    This command provides different operations on VEX-/SBOM- Files with embedded vulnerabilities. The vex-command has the following subcommands:
VEX-/SBOM-file (if you want to keep it consistent with the text later one, where you also only refer to is as "SBOM-file". Though the "-" is not even required.

2025-04-20 20:43 UTC, italvi commented on docs/source/usage/vex.rst
> +    This subcommand searches a file for a specific vulnerability based on its ID. The command returns a .json file.
JSON file

2025-04-20 20:43 UTC, italvi commented on docs/source/usage/vex.rst
> +    This subcommand extracts all vulnerabilities from a SBOM-file and returns it as a VEX-file in .json format
JSON format. (dot at the end of the sentence is also missing)

2025-04-20 20:43 UTC, italvi commented on cdxev/__main__.py
> +        help=("The path to the input file. (SBOM or VEX file)"),
The dot should be after the brackets or you could even make a small adjustment lik "The path to the input (SBOM or VEX) file."

2025-04-22 05:51 UTC, italvi commented on cdxev/__main__.py
> +            usage_error("--key is required.", args.parser)
Why not first check for none, before assigning or then at least use the key for the check?

2025-04-22 05:53 UTC, italvi commented on cdxev/__main__.py
> +    schema = ""
vul_id is also assigned as empty string, per default, in the `vex`-function itself, so why is it here initialized, too? Would prefer the same handling for all of these variables.

2025-04-22 05:54 UTC, italvi commented on docs/source/usage/vex.rst
> +    This subcommand extracts all vulnerabilities from a SBOM-file and returns it as a VEX-file in .json format
an SBOM-file

2025-04-22 05:56 UTC, italvi commented on docs/source/usage/vex.rst
> +    The output can be a .txt file or a .csv (default) file.
text or a CSV

2025-04-24 07:31 UTC, CBeck-96 commented on docs/source/usage/vex.rst
> +        CVE-1013-0003
Fixed

2025-04-24 07:33 UTC, CBeck-96 commented on docs/source/usage/vex.rst
> +    This subcommand searches a file for a specific vulnerability based on its ID. The command returns a .json file.
Done

2025-04-24 07:33 UTC, CBeck-96 commented on docs/source/usage/vex.rst
> +    This subcommand extracts all vulnerabilities from a SBOM-file and returns it as a VEX-file in .json format
Done

2025-04-24 07:34 UTC, CBeck-96 commented on docs/source/usage/vex.rst
> +    The output can be a .txt file or a .csv (default) file.
Done

2025-04-24 07:43 UTC, CBeck-96 commented on cdxev/__main__.py
> +        help=("The path to the input file. (SBOM or VEX file)"),
Done

2025-04-24 07:49 UTC, CBeck-96 commented on docs/source/usage/vex.rst
> +    This subcommand extracts all vulnerabilities from a SBOM-file and returns it as a VEX-file in .json format
Done

2025-04-24 09:57 UTC, CBeck-96 commented on cdxev/__main__.py
> +            usage_error("--key is required.", args.parser)
Refacored

2025-04-24 09:57 UTC, CBeck-96 commented on cdxev/__main__.py
> +    schema = ""
Removed

2025-04-25 13:59 UTC, italvi requested changes
Please see comments.

2025-04-25 13:59 UTC, italvi commented on docs/source/usage/vex.rst
Please build this locally and check your output. You are creating duplicate entries:
![image](https://github.com/user-attachments/assets/a141874d-4cbe-4a61-ae59-597d3c089a32)
One time without additional info:
![image](https://github.com/user-attachments/assets/a55ad83f-d3d3-4f43-a3bb-e77d61ff694f)
Then the command again:
![image](https://github.com/user-attachments/assets/dd098df6-e783-4c1e-be74-d6913840711d)

2025-04-25 13:59 UTC, italvi commented on docs/source/usage/vex.rst
> +    * ``extract``: extract all vulnerabilities from an SBOMfile to a VEXfile.
there is a whitespace missing between SBOM/VEX and file.

2025-04-25 13:59 UTC, italvi commented on docs/source/usage/vex.rst
> +    This subcommand extracts all vulnerabilities from an SBOMfile and returns it as a VEXfile in JSON format.
whitespace missing between SBOM/VEX and file.

2025-04-25 13:59 UTC, italvi commented on cdxev/__main__.py
> +    if args.sub_command == "list":
why a second if for the list? You have it just two lines above.

2025-04-25 13:59 UTC, italvi commented on docs/source/usage/vex.rst
> +    This command provides different operations on VEX/SBOM Files with embedded vulnerabilities. The vex-command has the following subcommands:
files

2025-04-28 10:44 UTC, CBeck-96 commented on docs/source/usage/vex.rst
> +    This subcommand extracts all vulnerabilities from an SBOMfile and returns it as a VEXfile in JSON format.
Done

2025-04-28 10:44 UTC, CBeck-96 commented on docs/source/usage/vex.rst
> +    * ``extract``: extract all vulnerabilities from an SBOMfile to a VEXfile.
Done

2025-04-28 10:45 UTC, CBeck-96 commented on docs/source/usage/vex.rst
> +    This command provides different operations on VEX/SBOM Files with embedded vulnerabilities. The vex-command has the following subcommands:
Done

2025-04-28 11:34 UTC, CBeck-96 commented on cdxev/__main__.py
> +    if args.sub_command == "list":
Refactored

2025-04-28 11:49 UTC, CBeck-96 commented on docs/source/usage/vex.rst
The documentation is now fixed, but the warnings still remain.

2025-04-28 16:57 UTC, italvi commented on docs/source/usage/vex.rst
There is an open [PR](https://github.com/sphinx-doc/sphinx-argparse/pull/62) in the used extension. However, it seems there is no maintainer. So we should look for an alternative. But as this is now not part of this PR, we can live with this issue. It's only a problem when we want to reference something in there, which is not that likely for a subcommand of a command.

2025-04-28 17:16 UTC, italvi approved these changes
lgtm now, thanks!

2025-04-28 17:16 UTC, merged